[model.HuggingFace]
# repo = "MaziyarPanahi/calme-2.1-qwen2-72b-GGUF"
# model = "Qwen2-72B-Instruct-v0.1.Q4_K_M-00001-of-00008.gguf"
repo = "QuantFactory/dolphin-2.9-llama3-8b-GGUF"
model = "dolphin-2.9-llama3-8b.Q4_0.gguf"
# repo = "bartowski/gemma-2-9b-it-GGUF"
# model = "gemma-2-9b-it-Q4_K_M.gguf"
# repo = "internlm/internlm2_5-7b-chat-gguf"
# model = "internlm2_5-7b-chat-q4_k_m.gguf"
# repo = "QuantFactory/Mistral-Nemo-Instruct-2407-GGUF"
# model = "Mistral-Nemo-Instruct-2407.Q4_1.gguf"
# repo =  "lmstudio-community/Meta-Llama-3.1-8B-Instruct-GGUF"
# model = "Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf"
# repo = "mlabonne/Meta-Llama-3.1-8B-Instruct-abliterated-GGUF"
# model = "meta-llama-3.1-8b-instruct-abliterated.Q4_0.gguf"
# repo = "MaziyarPanahi/calme-2.1-qwen2-7b-GGUF"
# model = "Qwen2-7B-Instruct-v0.1.Q4_K_M.gguf"
# repo = "MaziyarPanahi/calme-2.8-qwen2-7b-GGUF"
# model = "Qwen2-7B-Instruct-v0.8.Q4_K_M.gguf"
# repo = "Qwen/Qwen2-7B-Instruct-GGUF"
# model = "qwen2-7b-instruct-q4_k.gguf"

# [[scripts]]
# path = "./scripts/exec.lua"

# [[scripts.tasks]]
# # Crron order: sec  min  hour  day of month  month  day of week  year
# chron = "10  *  *  *  *  *  *"
# name = "Eval"

[[scripts]]
path = "./scripts/test.lua"

[[scripts.tasks]]
# Cron order: sec  min  hour  day of month  month  day of week  year
cron = "0  *  *  *  *  *  *"
name = "Test"
